### ISSUE TITLE
Premature Auditing Record for Resend Repository Action

### ISSUE THREAD

**Issue by tjdurden** [surevine/gateway-management#44]
With release export sanitisation applied, I hit the Resend button in the Gateway Management console.
Whilst viewing the /opt/gateway/console/gateway-management-1.0/logs/application.log, noticed the following INFO entry was logged out:

2015-01-26 17:30:52,339 - [INFO] - from application in play-akka.actor.default-dispatcher-105
[2015-01-26T17:30:52.339Z][**********)][Resent repository Battenburg(cake/battenburg) resent to destination Gitlab 1a(file:///tmp/testing/gitlab1a)]

Ideally, this should not have been thrown at this stage, as the repo was not resent / distributed because it failed sanitisation. Wondering if we could improve this?

**Comment by JonnyHeavey** [comment]
Due to the system architecture it will be difficult for the management console to determine whether the export was an overall success (as many plugins in the gateway could reject the export). As such, I think the best solution here would be to change the wording of the log message to state the the project 'was sent to the gateway for export', to better set the users expectations.
